### ISSUE TITLE
Custom ticking sounds don't work after resuming from sleep

### ISSUE THREAD

**Issue by mystilleef** [gnome-pomodoro/gnome-pomodoro#610]
## Issue Summary

When my computer resumes from sleep, custom ticking sounds stop working. I often have to toggle `Prefrences -> Plugins... -> Sounds` to get it working again.

## Steps to Reproduce

1. Enable ticking sounds 
2. Set a custom mp3 sound
3. Start a pomodoro session 
4. Wait for computer to sleep or suspend
5. Continue or restart pomodoro session
6. Sometimes pausing and unpausing the session looses ticking sounds.

## Context (logs, error output, screencast, OS, Desktop  etc)
I'm on:

```
Fedora package: gnome-pomodoro-1:0.20.0-1.fc35.x86_64
Pomodoro 0.20.0
Fedora Linux 35 (Workstation Edition)
GNOME Version 41.3 (Wayland)
```

## Expected Behavior

Custom ticking sounds should always play during pomodoro sessions.

## Possible Solution

It seems this might be an issue with settings not sticking.

## Other information

I've linked the custom ticking sound that I use below. It's a 185mb mp3 of 3 hours of white noise.

https://drive.google.com/file/d/1ZP0rRPpc6hjOWSQOP-OfTShSEfzJPL7E/view?usp=sharing

**Comment by mystilleef** [comment]
The workaround for those experiencing this issue is to use `Custom Actions`. Create shell scripts to play your custom ticking sounds. Then use the triggers in `Custom Actions` to trigger when the sound should start or stop playing.

**Comment by kamilprusko** [comment]
@mystilleef Thanks for reporting the issue. I'll look into this.

**Comment by kamilprusko** [comment]
I pushed a patch to master branch 13035390d644fc9bea2f6dd9879cf3a6107bc5b4 . Improving error handling to retry playing the sound in case of an error. 

Only, I don't experience this issue. Not sure if it will solve it.

**Comment by jayschauer** [comment]
I am on PopOS and I think I am experiencing a similar issue, maybe after locking my computer? Restarting my computer made the sounds work again. I am not using custom sounds, just the default ticking / birds. Turning the sound setting off and on or re-selecting it didn't fix it.
