### ISSUE TITLE
Cannot leave the "take a break" overlay

### ISSUE THREAD

**Issue by etuardu** [gnome-pomodoro/gnome-pomodoro#635]
## Issue Summary
Once the "take a break" overlay appears it is not possible to leave it. Moving the mouse or pressing Esc do not work.

## Steps to Reproduce
1. start gnome pomodoro
2. wait until the "take a break" screen appears
3. try to override the break using input controls

## Context (logs, error output, screencast, OS, Desktop  etc)
* GNOME Shell 42.3.1
* Pop!_OS 22.04 LTS (just upgraded from previous version)
* Pomodoro 0.20.0

## Expected Behavior
The user should be able to override the break as usual using input controls like moving the mouse or pressing Esc.

## Current Behavior
The user is trapped into the "Take a break" screen.

**Comment by lguenth** [comment]
This also happens on vanilla Ubuntu 22.04 LTS, with Wayland, and Pomodoro 0.20.0.

**Comment by etuardu** [comment]
Some further details:

- In spite of the modal overlay, a few keystrokes are captured by the system, so I manage to perform some actions such as:
  -  toggling overview mode pressing `Super`
  - move to next or previous desktop pressing `Ctrl`+`Alt`+`Up Arrow` or `Ctrl`+`Alt`+`Down Arrow`
  - Locking the screen pressing `Super`+`L`
- If I wait till the end of the break, the countdown will stop running at `0:01` and the overlay will stay there

**Comment by tymmek** [comment]
Any idea how to kill the overlay process? what is it called?
I tried
`ps aux | grep "pomodoro"`
and manually looked through the entire output of `ps aux` ...

**Comment by lonix1** [comment]
Be careful not to kill the `gnome-pomodoro` process itself, as the the desktop becomes unstable. I needed to log into another session alt+f3, and reboot!

**Comment by eduarddrenth** [comment]
killing pomodoro doesn't help, killing all my processes and logging in again helps, no need to reboot

**Comment by bablf** [comment]
same for me. Ubuntu 22.04 LTS. Commenting for visibility  .

**Comment by prahal** [comment]
Patch 622 is already merged in a release from this repository. https://github.com/gnome-pomodoro/gnome-pomodoro/commit/381f215469f7706c36284bafdb8cdee96a39db7a since https://github.com/gnome-pomodoro/gnome-pomodoro/pull/622. You should bug your distribution for an issue fixed in an upstream release here 0.21.1 but not in your distribution release.

Or it could be you suffer from https://github.com/gnome-pomodoro/gnome-pomodoro/issues/604 which fix is already merged https://github.com/gnome-pomodoro/gnome-pomodoro/pull/630, but not yet tagged, in a release. In which case it is a duplicate.

In both cases, this issue should be closed.

**Comment by pfuhlert** [comment]
I have the same problem with Ubuntu 22.04, gnome 42.5, pomodoro 0.22.1

The problem was fixed at first but today I experienced that I couldnt leave the pause screen when I was inside a zoom meeting watching someone share a screen. Maybe adding a fail safe hotkey to terminate the pause screen would be a good idea?

**Comment by pfuhlert** [comment]
That would even be better. I forgot to mention that I was viewing zoom screen sharing on full screen. So maybe some option like "avoid on fullscreen" (as in video fullscreen) would also be a good idea.

**Comment by trolliama** [comment]
I noticed that (In my case) every time I stop moving my mouse moments before the break starts I am able to leave the pause screen. Here is my issue: #641

**Comment by dawaltconley** [comment]
Building 0.22.1 from source seems to have fixed the issue for me on Pop_OS! 22.04, gnome-shell 42.3.1.

With 0.20.0 from the repo, the problem was also resolved if I disabled the Pomodoro shell extension (via Extensions) and then ran the app. The overlay still appeared but the DE wouldn't freeze and it can be dismissed. May help others.

Also, when it freezes, I was able to fix it without logging out by killing and restarting gnome: `killall -HUP gnome-shell`

**Comment by kamilprusko** [comment]
Made progress on this...
- added a failsafe handler for the Esc key
- added additional way of detecting user activity (this caused issue with video call apps, as they are faking user activity to keep screen awake)
- the overlay won't open automatically when the webcam is on, or when a video call app is fullscreen (must be an app,  not a web browser)

I don't see a good way to detect whether microphone is active in case sharing a screen without webcam.

> I'd be interested in an option to keep the shell extension but disable the overlay.

@dawaltconley You can disable it:
![Screenshot from 2022-12-31 14-29-28](https://user-images.githubusercontent.com/1135423/210138537-fc4679d8-289a-4cde-b331-d75a29c10002.png)

**Comment by real-or-random** [comment]
I'm seeing this with 0.22.0:

 - If and only if there's an active "wakelock", e.g., in a zoom call or when I enable https://extensions.gnome.org/extension/517/caffeine/ , then I can't exit the overlay. (I need `killall -HUP gnome-shell` which works great as a last resort).  

(Maybe your recent progress solves this but I haven't tested.)


> > I'd be interested in an option to keep the shell extension but disable the overlay.
> 
> (...) You can disable it: ![Screenshot from 2022-12-31 14-29-28](https://user-images.githubusercontent.com/1135423/210138537-fc4679d8-289a-4cde-b331-d75a29c10002.png)

Ah that's awesome, this makes the issue much less severe.

**Comment by henioStraszny** [comment]
> I have the same problem with Ubuntu 22.04, gnome 42.5, pomodoro 0.22.1
> 
> The problem was fixed at first but today I experienced that I couldnt leave the pause screen when I was inside a zoom meeting watching someone share a screen. Maybe adding a fail safe hotkey to terminate the pause screen would be a good idea?

How did you get version 0.22.1 ? I can't see this tag in GIT.

**Comment by real-or-random** [comment]
> How did you get version 0.22.1 ? I can't see this tag in GIT.

It's not tagged but if you build master, the extension will show 0.22.1 as a version number.



> I'm seeing this with 0.22.0:
> 
>     * If and only if there's an active "wakelock", e.g., in a zoom call or when I enable [extensions.gnome.org/extension/517/caffeine](https://extensions.gnome.org/extension/517/caffeine/) , then I can't exit the overlay. (I need `killall -HUP gnome-shell` which works great as a last resort).
> 
> 
> (Maybe your recent progress solves this but I haven't tested.)

Ok this problem is gone. I can now exit the overlay even with a wakelock.

(However, now I see another problem: the overlay doesn't start at all unless I click the notification. I suspect this is due to https://github.com/gnome-pomodoro/gnome-pomodoro/commit/50456e077194d8e42f8b6ac232d4348c1acdaada, I commented there.)

**Comment by kamilprusko** [comment]
Tagged a release [0.22.1](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.22.1) with fixes mentioned earlier.

The webcam detection caused screen overlay not to open at times. It got reverted.

**Comment by andrm** [comment]
I'm on Fedora 37, 0.22.0 from dnf, overlay comes on and does not exit if I'm in a jitsi call.

**Comment by Pictor13** [comment]
@andrm Jitsi app or Jitsi webapp?
Above was mentioned that call detection won't work for webapps.

**Comment by kamilprusko** [comment]
In `master`, `gnome-45` and `gnome-46` branches landed an updated overlay.

It's now possible to dismiss the overlay when a video is playing. It comes at expense of stealing focus when fade-in animation is done. I think it's an acceptable compromise since there is 10s announcement. Closing the overlay is somewhat easier as delays have been reduced and there's an indicator as to when the overlay is blocking the inputs...

There's also a hidden option (accessible via _dconf editor_ app) to just use buttons.

![Screenshot from 2024-07-07 15-25-48](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/1135423/75a945fc-ca3a-4fb1-95a6-acf027f9fe32)
![Screenshot from 2024-07-07 15-29-02](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/1135423/13928e01-43df-4cac-90de-6c878227881f)
![Screenshot from 2024-07-07 15-29-43](https://github.com/gnome-pomodoro/gnome-pomodoro/assets/1135423/1e9b252b-7b85-4d3c-a9c4-862ed0280162)
